[book]
authors = ["Hemanth Reddy", "Michel Langhammer"]
src = "src"
title = "LAUDS Gateway Wiki"
language = "en"

[output.html]
additional-css = ["src/theme/extra.css"]
default-theme = "light"
preferred-dark-theme = "navy"
smart-punctuation = true
git-repository-url = "https://github.com/new-production-institute/wiki-lauds-gateway-applications"
edit-url-template = "https://github.com/new-production-institute/wiki-lauds-gateway-applications/edit/main/{path}"

[output.html.fold]
enable = true
level = 0